services:
  postgres17_loans_db:
    image: postgres:17
    container_name: postgres17_loans_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "loans_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "@admin1"
    ports:
      - "5433:5432"
    volumes:
      - ./01_create_schema_loans.sql:/docker-entrypoint-initdb.d/01_create_schema_loans.sql
      - postgrest17_loans_db_vol:/var/lib/postgresql/data
volumes:
  postgrest17_loans_db_vol: